openimsdk/chat

pkg/common/db/model/admin/admin.go

add prompt msg

---

.github/dependabot.yml
Makefile
internal/rpc/chat/statistic.go
scripts/check_all.sh
scripts/path_info.sh
scripts/stop_all.sh

fix: script absolute path problem

---

internal/api/admin.go
internal/api/chat.go
internal/api/router.go

move deletelog api to admin router group

---

pkg/common/chatrpcstart/start.go

feat: make listening only after connection to components prepared

---

pkg/common/config/parse.go
pkg/common/constant/constant.go

fix: fix the flag parse

---

.github/workflows/docker-buildx.yml

feat: openim-chat super docker images aliyun and docker hub

---

scripts/path_info.sh

<br>
Fixes #
runs well on mac with m1 chip.

feat: add supported architechture

---

config/config.yaml
internal/api/mw.go
internal/api/router.go
internal/rpc/chat/login.go
pkg/common/mw/gin_log.go
pkg/proto/chat/chat.go

fix: default verifyCode type and admin register user

---

internal/api/admin.go
internal/api/chat.go
internal/api/router.go
pkg/common/apistruct/chat.go

feat: add a callback example that receive the message and return

---

deployments/templates/config.yaml

<br>
/kind feature
This Pull Request addresses an issue specific to deployment on macOS, where database names are automatically converted from uppercase to lowercase. This behavior can lead to inconsistencies and potential issues in environments where case sensitivity is important.
- Implemented a fix that ensures all database names are initialized in lowercase. This applies to all instances where databases are created or referenced within the system.
- Added checks to prevent the creation of databases with uppercase names, enforcing a lowercase naming convention across the platform.
- This change promotes consistency in database naming conventions, particularly in cross-platform setups.
- It prevents the potential issues that arise from the automatic conversion of …

Fix(release-v1.5): Ensure Database Names are Initialized in Lowercase on macOS

---

.github/workflows/scripts-test.yml
scripts/admin_rpc_start.sh
scripts/build_all_service.sh
scripts/check_all.sh
scripts/docker_start_all.sh
scripts/start_all.sh

This PR focuses on enhancing our log management system, particularly by adjusting the startup log path for the chat service. Previously, the startup logs for the chat service were located in the `logs/` directory. This setup caused inconsistencies in path management and inconveniences in maintenance. To address this issue, we have decided to migrate the chat startup log path to `_output/logs`.
This change aligns the chat service's log path with that of our openim-server, unifying our project's log management approach. It also makes log storage and access more intuitive and efficient. This update is aimed at simplifying our log maintenance efforts and providing a more convenient path for future log analysis.
Key changes include:
1. Modifying the log path configuration for the chat service …

Standardizing Log Path: Migrating chat Service Startup Logs to _output/logs

---

HOW_TO_SETUP_LIVEKIT_SERVER.md
README.md

Update README to add link to 'How to Setup LiveKit Server' document.

---

Dockerfile
build/images/api-admin/Dockerfile
build/images/api-chat/Dockerfile
build/images/rpc-admin/Dockerfile
build/images/rpc-chat/Dockerfile

docs: sora zh readme from awesome

---

.github/code-language-detector.yml
.github/workflows/language-check.yml

<br>
/kind feature
"A GitHub Action for detecting specified languages (e.g., Chinese or Japanese) in comments within code files across multiple programming languages (YAML, Go, Java, Rust). Ideal for projects aiming to adhere to internationalization standards or maintain language-specific coding guidelines."
+ [https://github.com/marketplace/actions/code-language-detector](https://github.com/marketplace/actions/code-language-detector)

add github actions is create code-language-detector.yml

---

Makefile

<br>
/kind flake
This PR represents a crucial update to our chat application's compatibility matrix by modifying the minimum version requirement to embrace a broader range of Go supported versions. Specifically, we are expanding the GO_SUPPORTED_VERSIONS parameter to include versions 1.21, 1.22, 1.23, and 1.24. This adjustment ensures our application remains aligned with current Go standards, offering enhanced stability, security, and performance benefits inherent in these versions. By accommodating a wider spectrum of Go environments, we are not only future-proofing our application but also providing our developers and users with the flexibility to operate within their preferred Go ecosystem. This update underscores our commitment to leveraging cutting-edge technology to deliver a robust …

cicd: update chat makefile fix go version minimun 1.21

---

.dockerignore
.gitignore
Dockerfile
go.mod
go.sum
start-config.yml

Optimize the Dockerfile.

---

Dockerfile
config/chat-api-admin.yml
config/chat-api-chat.yml
config/chat-rpc-admin.yml
config/chat-rpc-chat.yml
config/log.yml
config/mongodb.yml
config/redis.yml
config/share.yml
config/zookeeper.yml
go.mod
go.sum
pkg/common/db/model/admin/ip_forbidden.go
pkg/common/db/table/admin/admin.go
pkg/common/db/table/admin/client_config.go
pkg/common/db/table/admin/forbidden_account.go
pkg/common/db/table/admin/invitation_register.go
pkg/common/db/table/admin/ip_forbidden.go
pkg/common/db/table/admin/limit_user_login_ip.go
pkg/common/db/table/admin/register_add_friend.go
pkg/common/db/table/admin/register_add_group.go
pkg/common/db/table/chat/account.go
pkg/common/db/table/chat/attribute.go
pkg/common/db/table/chat/register.go
pkg/common/db/table/chat/user_login_record.go
pkg/common/xlsx/main.go
pkg/common/xlsx/utils.go
pkg/eerrs/predefine.go
pkg/email/mail.go

Add comments

---

.github/workflows/chatci.yml
.github/workflows/scripts-test.yml

Updata action

---

Dockerfile
go.mod
go.sum

update gomake version

---

pkg/common/db/model/chat/attribute.go

Fixes #599
fix: SearchFriend can search email

fix: SearchFriend can search email

---

internal/api/admin/config_manager.go
internal/api/admin/start.go
internal/api/chat/start.go
pkg/common/apistruct/config_manager.go
pkg/common/cmd/admin_api.go
pkg/common/cmd/admin_rpc.go
pkg/common/cmd/chat_api.go
pkg/common/cmd/chat_rpc.go
pkg/common/cmd/root.go
pkg/common/config/config.go
pkg/common/config/env.go
pkg/common/kdisc/etcd/config_manager.go
pkg/common/startrpc/start.go
tools/attribute-to-credential/main.go
tools/check-component/main.go

feat: config center

---

go.mod
go.sum
internal/api/admin/admin.go
internal/api/admin/config_manager.go
internal/api/admin/start.go
internal/api/chat/chat.go
internal/api/chat/start.go
pkg/common/apistruct/config_manager.go
pkg/common/cmd/admin_rpc.go
pkg/common/cmd/chat_rpc.go
pkg/common/cmd/root.go
pkg/common/kdisc/discoveryregister.go
pkg/common/kdisc/etcd/config_manager.go
pkg/common/kdisc/etcd/const.go
pkg/common/startrpc/start.go

feat: Add enable config center button &&  fix: grpc connection leakage

---

internal/rpc/chat/login.go

fix:  When the phone verification code is not passed in, the enable rule of the phone verification code still takes effect

---

config/README.md
config/README_zh_CN.md

docs: update config readme.

---

.github/workflows/update-version-file-on-release.yml

feat: add safe submodule init in v1.8.4-patch
