pkg/proto/admin/admin.go, pkg/proto/chat/chat.go
=> add parameter check

go.mod, go.sum
=> fix: sql injection risk

scripts/start_all.sh
bug: fix merge caused start_all.sh can not find such path
<br>
Fixes #67
=> bug: fix start_all.sh by merge fault

.goreleaser.yaml, cmd/api/admin_api/main.go, cmd/api/chat_api/main.go, cmd/rpc/admin/main.go, cmd/rpc/chat/main.go, pkg/common/config/parse.go, scripts/start_all.sh
Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com><br>
/kind feature
Fixes #
=> fix: args check

config/config.yaml, pkg/common/config/config.go, pkg/common/config/parse.go, pkg/common/db/cache/init_redis.go
Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com><br>
Fixes #
=> fix: chat config path

.github/workflows/build-docker-image.yml, .github/workflows/docker-buildx.yml, .github/workflows/release.yml, .github/workflows/scripts-test.yml, .github/workflows/test_2.yml, .github/workflows/test_buildx.yml, .goreleaser.yaml
=> feat: test actions

pkg/proto/chat/chat.go
=> reset password parameter err

scripts/start_all.sh
=> feat: add scripts test

cmd/api/admin_api/main.go, cmd/api/chat_api/main.go, cmd/rpc/admin/main.go, cmd/rpc/chat/main.go, go.mod, go.sum
=> fix: startup cpu usage is too high

.github/workflows/release.yml, .goreleaser.yaml
=> fix: delete config secret

.github/workflows/auto-gh-pr.yml, .github/workflows/auto-tag.yml
<br>
/kind feature
Fixes OpenIMSDK/Open-IM-Server#406
=> feat: add add labels

internal/rpc/chat/login.go, internal/rpc/chat/password.go
<br>
Fixes #OpenIMSDK/Open-IM-Server#750
=> Fix the parameter error in verifying the captcha when logging in with the captcha and retrieving the password with the captcha

internal/api/chat.go
=> fix: im api UserToken error non-responsive body

.github/workflows/scripts-test.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, Dockerfile, Makefile, build/docker/api-admin/Dockerfile, build/docker/api-chat/Dockerfile, build/docker/rpc-admin/Dockerfile, build/docker/rpc-chat/Dockerfile, scripts/build_all_service.sh, scripts/check_all.sh, scripts/start_all.sh
<br>
/kind feature
Resolves OpenIMSDK/Open-IM-Server#783, resolves OpenIMSDK/Open-IM-Server#788,  resolves OpenIMSDK/Open-IM-Server#784,  resolves OpenIMSDK/Open-IM-Server#785
Link: OpenIMSDK/Open-IM-Server#782
=> fix: docker images version

cmd/api/admin-api/main.go, cmd/api/chat-api/main.go, cmd/rpc/admin-rpc/main.go, cmd/rpc/chat-rpc/main.go, internal/api/chat.go
=> fix: random seed not set

scripts/admin_rpc_start.sh, scripts/build_all_service.sh, scripts/build_docker.sh, scripts/check_all.sh, scripts/docker_start_all.sh, scripts/function.sh, scripts/githooks/commit-msg, scripts/githooks/pre-commit, scripts/githooks/pre-push, scripts/path_info.sh, scripts/start_all.sh, scripts/stop_all.sh, scripts/style_info.sh, test/common.sh
=> feat: add chat details

scripts/build_all_service.sh, scripts/check_all.sh, scripts/start_all.sh, scripts/stop_all.sh
=> check_all scripts can't check if the service has started and stop_all script can't stop all service

scripts/check_all.sh, scripts/start_all.sh
=> start_all doesn't kill the old service

.github/sync.yml, .github/workflows/sync.yml, Dockerfile, build/docker/api-admin/Dockerfile, build/docker/api-chat/Dockerfile, build/docker/rpc-admin/Dockerfile, build/docker/rpc-chat/Dockerfile, scripts/docker_start_all.sh
Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com><br>
/kind feature
https://github.com/openim-sigs/openim-base-image/
https://github.com/openim-sigs/openim-docker
=> fix: chat scripts path bug

cmd/api/admin-api/main.go, cmd/api/chat-api/main.go, cmd/rpc/admin-rpc/main.go, cmd/rpc/chat-rpc/main.go, tools/component/component.go
=> config check

.github/sync-release.yml, .github/workflows/sync-release.yml
<br>
/kind feature
LinK PR https://github.com/OpenIMSDK/Open-IM-Server/pull/962
Fixes https://github.com/OpenIMSDK/Open-IM-Server/issues/961
=> feat: add openim-docker design

scripts/check_all.sh, scripts/docker_start_all.sh
Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com><br>
/kind feature
Fixes #
=> feat: add test file code

config/config.yaml
=> fix: Zk port after openim refactoring config

Makefile, build/docker/api-admin/Dockerfile, build/docker/api-chat/Dockerfile, build/docker/rpc-admin/Dockerfile, build/docker/rpc-chat/Dockerfile
<br>
/kind feature
Docker and build 
Fixes #178
=> feat: super chat makefile build

README.md
=> feat: openim-chat makefile super

scripts/check_all.sh
<br>
/kind bug
/kind cleanup
/kind feature
=> fix: fix chat scripts user docker and loacl deployment update check_all.sh

scripts/check_all.sh
=> fix: script print

README.md, scripts/check_all.sh
=> feat: openim-chat makefile super (#185)

README.md
<br>
/kind feature
Fixes #198
no 
```
make check
```
```
./scripts/check.sh --print-screen
```
-->
=> docs: update readme about check

pkg/common/chatrpcstart/start.go, scripts/start_all.sh
/kind feature
feat:check and build binary if needed when make start
Fixes #209 
make clean
make start
=> Feat/fixscript:check and build binary if needed when make start

.github/workflows/scripts-test.yml, Dockerfile, Makefile, README.md, config/config.yaml.template
Signed-off-by: Xinwei Xiong(cubxxw) <3293172751nss@gmail.com>
Fixed: #284
=> feat: add openim chat fix support v3.5 install

Dockerfile
=> fix: Image Dockerfile Update Dockerfile

.github/workflows/scripts-test.yml, scripts/build_all_service.sh, scripts/stop_all.sh
fix macOs lscpu  ps aux
macos bug fix
=> fix macOs cpu_count

cmd/api/admin-api/main.go, cmd/api/chat-api/main.go, cmd/rpc/admin-rpc/main.go, cmd/rpc/chat-rpc/main.go, pkg/common/apicall/call.go, pkg/common/config/parse.go, pkg/common/db/cache/init_redis.go, pkg/discovery_register/k8s_discovery_register.go, tools/component/component.go
=> update init config

scripts/check_all.sh
=> fix bug: read port information from the configuration file.

.goreleaser.yaml, scripts/check_all.sh
=> Fix bug 365

.gitignore
Update .gitignore add components
=> Update .gitignore add components

README.md
=> Update README release3.4 to release3.5

go.mod, go.sum, pkg/common/tokenverify/token_verify.go
=> fix: del the open-util pkg

go.mod, go.sum, pkg/common/chatrpcstart/start.go, pkg/common/tokenverify/token_verify.go
=> fix: replace the open_utils pkg and del the unuse pkg

deployments/templates/config.yaml
<br>
/kind feature
This Pull Request addresses an issue specific to deployment on macOS, where database names are automatically converted from uppercase to lowercase. This behavior can lead to inconsistencies and potential issues in environments where case sensitivity is important.
- Implemented a fix that ensures all database names are initialized in lowercase. This applies to all instances where databases are created or referenced within the system.
- Added checks to prevent the creation of databases with uppercase names, enforcing a lowercase naming convention across the platform.
- This change promotes consistency in database naming conventions, particularly in cross-platform setups.
- It prevents the potential issues that arise from the automatic conversion of …
=> Fix(main): Ensure Database Names are Initialized in Lowercase on macOS

README.md, scripts/check_all.sh, scripts/path_info.sh, scripts/start_all.sh
<br>
/kind feature
please assist with the deployment of openim-chat on Mac using this link
Fixes #220
User Mac test 
+ start mysql
```
make start 
make check
```
=> feat: supoort openim-chat source code deployment in mac

scripts/check_all.sh
<br>
/kind bug
```
➜  chat git:(main) ✗ make check              
===========> Checking the service
================> Architecture: arm64
================> BIN_DIR: /Users/kevin/test/chat/scripts/..//Users/kevin/test/chat/scripts/../_output/bin/platforms/darwin/arm64
10009 port has been listening, belongs service is admin-api
30300 port has been listening, belongs service is chat-rpc
30200 port has been listening, belongs service is admin-rpc
10008 port has been listening, belongs service is chat-api
```
Mac System:
```
make check
```
=> update check_all.sh fix mac check scripts

scripts/check_all.sh
=> bug(main): update check_all fix chat scripts logs print

deployments/templates/config.yaml, pkg/common/apicall/caller.go, pkg/common/config/parse.go, pkg/common/db/model/admin/admin.go, pkg/common/mctx/get.go
=> feat: del the AdminList configure and it's init statement

scripts/admin_rpc_start.sh, scripts/build_all_service.sh, scripts/check_all.sh, scripts/docker_start_all.sh, scripts/path_info.sh, scripts/start_all.sh
Could you please assist with the deployment of the advanced version of the Mac in this PR
=> fix(release-v1.5): fix release-v1.5 scritps bug support mac deployment

.github/workflows/scripts-test.yml, deployments/helm-charts/config.yaml, deployments/templates/config.yaml, scripts/admin_rpc_start.sh, scripts/check_all.sh, scripts/docker_start_all.sh
<br>
/kind feature
optimize the log files for the chat system
=> feat: optimize openim reset code

pkg/common/dbconn/mongo.go
=> fix: mongo config struct

scripts/start-all.sh
=> fix: remove duplicate character.

deployments/templates/config.yaml
Could you please assist in removing the MySQL configuration part from this PR related to the chat feature? Thank you!
=> update config and remove  mysql conf

README.md, scripts/check-all.sh, scripts/docker-start-all.sh, scripts/start-all.sh, scripts/util.sh
=> Optimizing Docker-related scripts and logs

.github/workflows/chatci.yml
<br>
/kind feature
Fixes #
Could you please take a look at the CICD process? Thank you!
=> feat: add go typecheck actions

Makefile
<br>
/kind feature
add util test cover 75%
```
make cover
```
=> Update Makefile add test cover is 75

config/share.yml, internal/api/admin/start.go, internal/api/chat/start.go, internal/rpc/admin/start.go, pkg/common/config/config.go
=> feat: chat admin config

Dockerfile, config/chat-api-admin.yml, config/chat-api-chat.yml, config/chat-rpc-admin.yml, config/chat-rpc-chat.yml, config/log.yml, config/mongodb.yml, config/redis.yml, config/share.yml, config/zookeeper.yml, go.mod, go.sum, pkg/common/db/model/admin/ip_forbidden.go, pkg/common/db/table/admin/admin.go, pkg/common/db/table/admin/client_config.go, pkg/common/db/table/admin/forbidden_account.go, pkg/common/db/table/admin/invitation_register.go, pkg/common/db/table/admin/ip_forbidden.go, pkg/common/db/table/admin/limit_user_login_ip.go, pkg/common/db/table/admin/register_add_friend.go, pkg/common/db/table/admin/register_add_group.go, pkg/common/db/table/chat/account.go, pkg/common/db/table/chat/attribute.go, pkg/common/db/table/chat/register.go, pkg/common/db/table/chat/user_login_record.go, pkg/common/xlsx/main.go, pkg/common/xlsx/utils.go, pkg/eerrs/predefine.go, pkg/email/mail.go
=> Add comments

HOW_TO_SETUP_LIVEKIT_SERVER.md, docs/CODEOWNERS, livekit/livekit.yaml
=> docs: livekit quick start

livekit/livekit.yaml
=> fix: keep default livekit key same in config

HOW_TO_SETUP_LIVEKIT_SERVER.md, livekit/livekit.yaml
=> fix: assign livekit node ip

pkg/common/db/model/chat/credential.go
=> fix: Update user error

internal/api/admin/admin.go, pkg/common/imapi/caller.go
=> Fix Add User Api

internal/api/admin/admin.go, pkg/common/db/model/chat/attribute.go
Fixes #592
fix: search user && add user
=> fix: search user can search email && refactor addUser

internal/rpc/chat/login.go
Fixes #596
fix: login check remove psw check
=> fix: login check remove psw check

internal/rpc/chat/update.go
Fixes #603
fix: update user email error
=> fix: update user email error

internal/api/mw/mw.go, internal/rpc/admin/start.go, internal/rpc/admin/token.go, pkg/common/db/cache/token.go, pkg/common/db/database/admin.go, pkg/common/tokenverify/token_verify.go
=> fix: errors caused by too many tokens

internal/api/admin/admin.go, internal/api/chat/chat.go, pkg/common/imapi/caller.go, pkg/common/tokenverify/token_verify.go, tools/check-component/main.go
Fixes #
fix: admin token cache
=> fix: admin token cache

go.mod, go.sum
=> fix: Error will print stack

config/chat-rpc-chat.yml, internal/rpc/chat/login.go, internal/rpc/chat/password.go, internal/rpc/chat/start.go, pkg/common/config/config.go, pkg/common/constant/constant.go
=> feat: change verify code enable to use

.github/workflows/auto-invite-comment.yml, .github/workflows/auto-invite.yml, .github/workflows/help-comment-issue.yml, .github/workflows/merge-from-milestone.yml, .goreleaser.yaml, CONTRIBUTING.md, README.md, README_zh_CN.md
=> build: fix cancel when merge conflict.

pkg/common/imapi/caller.go
Fixes https://github.com/openimsdk/open-im-server/issues/3179
=> fix: deadlock in chat

internal/api/admin/config_manager.go, internal/api/admin/start.go, pkg/common/apistruct/config_manager.go
Fixes https://github.com/openimsdk/open-im-server/issues/3182
=> feat: set configs api

tools/dataversion/data_version.go
=> fix: data version SetVersion will add record

internal/rpc/chat/login.go
=> fix: verify mail constant

internal/rpc/chat/utils.go
=> fix: delete space in account

.github/workflows/merge-from-milestone.yml
=> fix: improve milestone PR workflow.

.github/workflows/update-version-file-on-release.yml
=> feat: add safe submodule init in pre-release-v1.8.5

go.mod, go.sum, magefile.go
=> refactor: support modified in mage tool.
